-- 008: Admin sessions for password-based dashboard login
CREATE TABLE IF NOT EXISTS _admin_sessions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    token TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ NOT NULL
);

-- Seed: initial password from DASHBOARD_API_KEY env var (set at runtime)
