ALTER TABLE customers ADD COLUMN surname TEXT NOT NULL DEFAULT '';
ALTER TABLE customers ADD COLUMN postal_code TEXT NOT NULL DEFAULT '';
ALTER TABLE customers ADD COLUMN email TEXT NOT NULL DEFAULT '';
ALTER TABLE customers ADD COLUMN province TEXT NOT NULL DEFAULT '';
