ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'pending';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS yoco_checkout_id TEXT UNIQUE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS yoco_event_id TEXT UNIQUE;
