-- 013: Multi-role + product enrichment + commission + stock
-- Zen Fragrances / PerfumeLine
-- 2026-07-28

-- ── Product categories (for 99 SKU browsing) ──
CREATE TABLE IF NOT EXISTS product_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    display_order INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS product_category_map (
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    category_id INTEGER NOT NULL REFERENCES product_categories(id) ON DELETE CASCADE,
    PRIMARY KEY (product_id, category_id)
);

-- ── Product enrichment for 99 SKU browsing ──
ALTER TABLE products ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS scent_family TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS top_notes TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT NULL;

-- ── Multi-role on customers ──
ALTER TABLE customers ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'customer';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS agent_code TEXT UNIQUE;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS registered_by INTEGER REFERENCES customers(id);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS recovery_pin TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS previous_phone_numbers TEXT DEFAULT '[]';

-- ── Commission + shipping on orders ──
ALTER TABLE orders ADD COLUMN IF NOT EXISTS agent_code TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS team_member_id INTEGER REFERENCES customers(id);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS commission_amount DECIMAL(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipping_method TEXT;

-- ── Indexes ──
CREATE INDEX IF NOT EXISTS idx_products_gender ON products(gender);
CREATE INDEX IF NOT EXISTS idx_products_scent_family ON products(scent_family);
CREATE INDEX IF NOT EXISTS idx_products_price ON products(price);
CREATE INDEX IF NOT EXISTS idx_agent_code ON customers(agent_code);
CREATE INDEX IF NOT EXISTS idx_customers_role ON customers(role);
CREATE INDEX IF NOT EXISTS idx_orders_agent_code ON orders(agent_code);
CREATE INDEX IF NOT EXISTS idx_orders_team_member_id ON orders(team_member_id);

-- ── Seed product categories ──
INSERT INTO product_categories (name, display_order) VALUES
    ('Woody', 1),
    ('Floral', 2),
    ('Oriental', 3),
    ('Fresh', 4),
    ('Citrus', 5),
    ('Aromatic', 6)
ON CONFLICT (name) DO NOTHING;
