from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from pathlib import Path

from src.config import Settings, get_settings


MIGRATIONS_DIR = Path(__file__).resolve().parent / "migrations"


@dataclass
class Database:
    mode: str
    connection: sqlite3.Connection | None = None
    pool: object | None = None


def _sqlite_row_to_dict(row: sqlite3.Row | None) -> dict | None:
    if row is None:
        return None
    return {key: row[key] for key in row.keys()}


def _adapt_sql_for_sqlite(sql: str) -> str:
    adapted = sql
    replacements = {
        "GENERATED BY DEFAULT AS IDENTITY": "AUTOINCREMENT",
        "TIMESTAMPTZ": "TIMESTAMP",
        "DEFAULT NOW()": "DEFAULT CURRENT_TIMESTAMP",
        "BOOLEAN": "INTEGER",
        "TRUE": "1",
        "FALSE": "0",
        "JSONB": "TEXT",
    }
    for old, new in replacements.items():
        adapted = adapted.replace(old, new)
    adapted = adapted.replace("INTEGER AUTOINCREMENT PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
    adapted = adapted.replace("INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL", "INTEGER PRIMARY KEY AUTOINCREMENT")
    adapted = adapted.replace("ALTER TABLE orders ADD COLUMN forwarded_at TIMESTAMPTZ;", "ALTER TABLE orders ADD COLUMN forwarded_at TIMESTAMP;")
    return adapted


async def connect_database(settings: Settings | None = None) -> Database:
    settings = settings or get_settings()
    if settings.database_mode == "postgres" and settings.database_url and settings.database_url.startswith("postgres"):
        import asyncpg

        pool = await asyncpg.create_pool(dsn=settings.database_url, min_size=1, max_size=5)
        return Database(mode="postgres", pool=pool)

    connection = sqlite3.connect(settings.local_sqlite_path)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return Database(mode="sqlite", connection=connection)


async def close_database(database: Database) -> None:
    if database.mode == "postgres" and database.pool is not None:
        await database.pool.close()
    if database.mode == "sqlite" and database.connection is not None:
        database.connection.close()


async def initialize_database(database: Database) -> None:
    for migration in sorted(MIGRATIONS_DIR.glob("*.sql")):
        version = int(migration.name.split("_", 1)[0])
        if await migration_applied(database, version):
            continue
        sql = migration.read_text(encoding="utf-8")
        await execute_script(database, sql)
        await record_migration(database, version, migration.name)


async def migration_applied(database: Database, version: int) -> bool:
    if database.mode == "postgres":
        assert database.pool is not None
        async with database.pool.acquire() as connection:
            await connection.execute(
                "CREATE TABLE IF NOT EXISTS _schema_migrations (version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TIMESTAMPTZ DEFAULT NOW())"
            )
            value = await connection.fetchval(
                "SELECT version FROM _schema_migrations WHERE version = $1",
                version,
            )
            return value is not None

    assert database.connection is not None
    database.connection.execute(
        "CREATE TABLE IF NOT EXISTS _schema_migrations (version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
    )
    row = database.connection.execute(
        "SELECT version FROM _schema_migrations WHERE version = ?",
        (version,),
    ).fetchone()
    return row is not None


async def record_migration(database: Database, version: int, name: str) -> None:
    if database.mode == "postgres":
        assert database.pool is not None
        async with database.pool.acquire() as connection:
            await connection.execute(
                "INSERT INTO _schema_migrations (version, name) VALUES ($1, $2)",
                version,
                name,
            )
        return

    assert database.connection is not None
    database.connection.execute(
        "INSERT INTO _schema_migrations (version, name) VALUES (?, ?)",
        (version, name),
    )
    database.connection.commit()


async def execute_script(database: Database, sql: str) -> None:
    if database.mode == "postgres":
        assert database.pool is not None
        async with database.pool.acquire() as connection:
            statements = [statement.strip() for statement in sql.split(";") if statement.strip()]
            for statement in statements:
                try:
                    await connection.execute(statement)
                except Exception as error:
                    if versionless_duplicate_column(error):
                        continue
                    raise
        return

    assert database.connection is not None
    script = _adapt_sql_for_sqlite(sql)
    statements = [statement.strip() for statement in script.split(";") if statement.strip()]
    for statement in statements:
        try:
            database.connection.execute(statement)
        except sqlite3.OperationalError as error:
            if "duplicate column name" in str(error).lower():
                continue
            raise
    database.connection.commit()


async def fetch_all(database: Database, query: str, *params: object) -> list[dict]:
    if database.mode == "postgres":
        assert database.pool is not None
        async with database.pool.acquire() as connection:
            rows = await connection.fetch(query, *params)
            return [dict(row) for row in rows]

    assert database.connection is not None
    rows = database.connection.execute(query, params).fetchall()
    return [{key: row[key] for key in row.keys()} for row in rows]


async def fetch_one(database: Database, query: str, *params: object) -> dict | None:
    if database.mode == "postgres":
        assert database.pool is not None
        async with database.pool.acquire() as connection:
            row = await connection.fetchrow(query, *params)
            return dict(row) if row else None

    assert database.connection is not None
    row = database.connection.execute(query, params).fetchone()
    return _sqlite_row_to_dict(row)


async def execute(database: Database, query: str, *params: object) -> None:
    if database.mode == "postgres":
        assert database.pool is not None
        async with database.pool.acquire() as connection:
            await connection.execute(query, *params)
        return

    assert database.connection is not None
    database.connection.execute(query, params)
    database.connection.commit()


def versionless_duplicate_column(error: Exception) -> bool:
    text = str(error).lower()
    return "duplicate_column" in text or "already exists" in text

